title: JRald blog
description: Gérald's technical blog about Java, Kafka, Elasticsearch, DevOps...
author: Gérald Quintana
email: gerald.quintana+blog@gmail.com
twitter_username: gerald_quintana
github_username:  gquintana
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - sources
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
  ext: adoc
