---
#{% raw %}
#tag::list_var[]
users:
  - id: bouh
    name: "Mary"
    admin: True
    role: child
  - id: sulli
    name: "James Sullivan"
    admin: False
    role: monster
  - id: bob
    name: "Bob Wazowski"
    admin: False
    role: assistant
  - id: celia
    name: "Celia Mae"
    admin: False
    role: assistant
#end::list_var[]

#tag::simple[]
admin_user_ids: |
  {{ users
  |selectattr('admin')
  |map(attribute='id')
  |join(',') }} #<1>
normal_user_count: |
  {{ users
  |rejectattr('admin')
  |list |count }} #<2>
#end::simple[]

#tag::select_advanced[]
assistant_user_ids: |
  {{ users
  |selectattr('role', 'equalto', 'assistant')
  |map(attribute='id')
  |join(',') }}
#end::select_advanced[]

#tag::map_advanced[]
user_first_names: |
  {{ users
  |map(attribute='name')
  |map('regex_replace', '(\\w+)( .*)?', '\\g<1>')
  |join(',') }} #<1>
#end::map_advanced[]

#tag::host_var[]
all_host_names: |
  {{ groups['all']
  |map('extract', hostvars, 'ansible_hostname')
  |join(',') }} #<1>
#end::host_var[]

#tag::json_query[]
jq_admin_user_ids: |
  {{ users
  |json_query("[?admin].id")
  |join(',') }} #<1>
jq_assistant_user_ids: |
  {{ users
  |json_query("[?role == 'assistant'].id")
  |join(',') }} #<2>
#end::json_query[]

#tag::json_query_error[]
jq_bid_user_ids: |
  {{ users
  |json_query("[?starts_with(id,'b')].id")
  |join(',') }}
#end::json_query_error[]
#{% endraw %}
